<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Func4Genexus</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <BaseIntermediateOutputPath>obj\Modern\</BaseIntermediateOutputPath>
    <OutputPath>bin\Modern\</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="GeneXus.Package.UI.Sdk" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Func4Genexus.catalog">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
