<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Func4Genexus_GX18_U14plus</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <BaseIntermediateOutputPath>obj\U14\</BaseIntermediateOutputPath>
    <OutputPath>bin\U14\</OutputPath>
    <DefineConstants>$(DefineConstants);GX18_U14</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <GeneXusPath Condition="'$(GeneXusPath)'=='' And Exists('C:\GeneXus\Gx18\U14')">C:\GeneXus\Gx18\U14</GeneXusPath>
    <GeneXusPath Condition="'$(GeneXusPath)'=='' And Exists('C:\GeneXus\Gx18\U13')">C:\GeneXus\Gx18\U13</GeneXusPath>
    <GeneXusPath Condition="'$(GeneXusPath)'==''">C:\GeneXus\Gx18U13_WWP16.08</GeneXusPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Artech.Common.Framework">
      <HintPath>$(GeneXusPath)\Artech.Common.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Udm.Framework">
      <HintPath>$(GeneXusPath)\Artech.Udm.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Common.Helpers">
      <HintPath>$(GeneXusPath)\Artech.Common.Helpers.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Common.Properties">
      <HintPath>$(GeneXusPath)\Artech.Common.Properties.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Architecture.Common">
      <HintPath>$(GeneXusPath)\Artech.Architecture.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Architecture.UI.Framework">
      <HintPath>$(GeneXusPath)\Artech.Architecture.UI.Framework.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Genexus.Common">
      <HintPath>$(GeneXusPath)\Artech.Genexus.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.UINative" Condition="Exists('$(GeneXusPath)\Artech.UINative.dll')">
      <HintPath>$(GeneXusPath)\Artech.UINative.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Artech.Common">
      <HintPath>$(GeneXusPath)\Artech.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GeneXusPath)\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Design" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Func4Genexus_U14.catalog">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Func4Genexus.package">
      <LogicalName>Func4Genexus_GX18_U14plus.Func4Genexus.package</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
